# Generated by Django 4.2.5 on 2023-11-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextoImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('parrafo', models.TextField(blank=True, max_length=100, null=True)),
                ('imagenes', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
