# Generated by Django 4.2.5 on 2023-11-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoimagenes',
            name='prueba',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
