# Generated by Django 4.2.5 on 2023-11-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_textoimagenes_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoimagenes',
            name='imagenes',
            field=models.ImageField(default='', upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
