# Generated by Django 4.2.5 on 2023-11-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_textoimagenes_imagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologíasYHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='imagenes/tyh_color')),
            ],
        ),
        migrations.CreateModel(
            name='TecnologíasYHerramientasBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='imagenes/tyh_gris')),
                ('parrafo', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='textoimagenes',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='textoimagenes',
            name='parrafo',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
