# Generated by Django 4.2.5 on 2023-11-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_tecnologíasyherramientas_tecnologíasyherramientasbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='imagenes/servicios')),
                ('parrafo', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tecnologíasyherramientasbn',
            name='parrafo',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
