# Generated by Django 4.2.7 on 2023-11-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_servicios_alter_tecnologíasyherramientasbn_parrafo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
